###Exercício 1.3
Crie variáveis para representar:

- nome de um produto;
- categoria;
- preço;
- quantidade em estoque;
- disponibilidade;
- código promocional opcional.

Depois:

1. mostre todos os valores;
2. mostre o tipo de cada variável;
3. substitua nomes genéricos por nomes descritivos.

In [ ]:
nome_produto = "Mouse"
categoria = "Periférico"
preco = 90000
qtd_estoque = 1
disponibilidade = "1 Mês"
cod_promocional = "MOUSE10"

In [ ]:
print(f"Nome do Produto: {nome_produto}\nCategoria do produto: {categoria}\nPreço do produto: {preco}\nQuantidade no estoque: {qtd_estoque}\nDisponibilidade: {disponibilidade}\nCódigo promocional: {cod_promocional}")

Nome do Produto: Mouse
Categoria do produto: Periférico
Preço do produto: 90000
Quantidade no estoque: 1
Disponibilidade: 1 Mês
Código promocional: MOUSE10

In [ ]:
print(f"A variável nome_produto é do tipo {type(nome_produto)}\nA variável categoria é do tipo {type(categoria)}\nA variável preco é do tipo {type(preco)}\nA variável qtd_estoque é do tipo {type(qtd_estoque)}\nA variável disponibilidade é do tipo {type(disponibilidade)}\nA variável cod_promocional é do tipo {type(cod_promocional)}")

A variável nome_produto é do tipo <class 'str'>
A variável categoria é do tipo <class 'str'>
A variável preco é do tipo <class 'int'>
A variável qtd_estoque é do tipo <class 'int'>
A variável disponibilidade é do tipo <class 'str'>
A variável cod_promocional é do tipo <class 'str'>

##Exemplo strip()

In [ ]:
nome = input("Nome do produto: ").strip()
preco = float(input("Preço unitário: "))
quantidade = int(input("Quantidade: "))

total = preco * quantidade

print(f"Produto: {nome}")
print(f"Total: R$ {total:.2f}")

KeyboardInterrupt: Interrupted by user

##1.4 Atividade de fixação
Crie um programa que solicite:

- nome do cliente;
- valor de uma compra;
- percentual de desconto.

O programa deve calcular e mostrar:

- valor do desconto;
- valor final;
- mensagem personalizada para o cliente.

In [ ]:
nome_cliente = input("Insira seu nome: ").strip()
valor_compra = float(input("Insira o valor da compra: "))
percentual_desconto = float(input("Insira o valor do desconto: "))

valor_desconto = valor_compra * (percentual_desconto / 100)

print(100 * "-")
print(f"{nome_cliente}, o valor final da compra foi de R${valor_compra - valor_desconto:.2f}. Muito obrigado pela preferência!")
print(100 * "-")

Insira seu nome: Nome
Insira o valor da compra: 100
Insira o valor do desconto: 50
----------------------------------------------------------------------------------------------------
Nome, o valor final da compra foi de R$50.00. Muito obrigado pela preferência!
----------------------------------------------------------------------------------------------------

##1.5 Atividade de fixação
Crie expressões para verificar se:

1. uma nota está entre 0 e 10;
2. uma pessoa possui 18 anos ou mais;
3. um produto está disponível e possui estoque maior que zero;
4. uma categoria pertence a uma lista permitida;
5. um usuário é administrador ou gerente.

In [ ]:
#Verificar se uma nota está entre 0 e 10.
nota = float(input("Insira uma nota qualquer: "))

if nota >= 0 and nota <= 10:
  print("A nota está entre 0 e 10!")
else:
  print("A nota não está entre 0 e 10.")

Insira uma nota qualquer: 100
A nota não está entre 0 e 10.

In [ ]:
#Verificar se uma pessoa possui de 18 anos ou mais.
idade = int(input("Insira a sua idade: "))

if idade >= 18:
  print("Você tem 18 anos ou mais!")
else:
  print("Você não tem 18 anos ou mais.")

Insira a sua idade: 10
Você não tem 18 anos ou mais.

In [ ]:
#Verificar se o produto está disponível e se tem o estoque maior que zero.
produto_disponivel = False
estoque_maior_zero = True

if produto_disponivel == True and estoque_maior_zero == True:
  print("O produto está disponível e tem estoque maior que zero!")
else:
  print("O produto não está disponível ou não tem o estoque maior que zero.")

O produto não está disponível ou não tem o estoque maior que zero.

In [ ]:
#Verificar se uma categoria inserida está dentro das categorias permitidas.

categoria = ["livro", "curso", "entretenimento"]

categoria_pesquisada = input("Insira a categoria que você quer descobrir se está permitida: ").lower()

if categoria_pesquisada in categoria:
  print(f"A categoria {categoria_pesquisada} está permitida!")
else:
  print(f"A categoria {categoria_pesquisada} não está permitida.")

Insira a categoria que você quer descobrir se está permitida: alimentação
A categoria alimentação não está permitida.

In [ ]:
categoria_pesquisada = input("Insira a categoria que você quer descobrir se não está permitida: ").lower()

if categoria_pesquisada not in categoria:
  print(f"A categoria {categoria_pesquisada} não está permitida!")
else:
  print(f"A categoria {categoria_pesquisada} está permitida.")

Insira a categoria que você quer descobrir se não está permitida: curso
A categoria curso está permitida.

In [ ]:
#Verificar se o usuário é administrador ou gerente.

id_usuario = input("Insira o seu ID: ")

if id_usuario.startswith("000"):
  print("O usuário é Administrador.")
else:
  print("O usuário é Gerente.")

Insira o seu ID: 001
O usuário é Gerente.

##1.6 Atividade de fixação
Solicite o nome completo de uma pessoa e mostre:

- nome sem espaços extras;
- nome em letras maiúsculas;
- quantidade de caracteres;
- primeiro nome;
- último nome;
- uma sugestão simples de nome de usuário.

In [ ]:
nome = input("Insira o seu nome completo: ")

Insira o seu nome completo: Heitor da Silva de Oliveira

In [ ]:
#Nome sem espaços extras.
print(nome.strip())

Heitor da Silva de Oliveira

In [ ]:
#Nome em letras maiúsculas.
print(nome.upper())

HEITOR DA SILVA DE OLIVEIRA

In [ ]:
#Quantidade de caracteres no nome.
print(len(nome))

27

In [ ]:
#Exibir somente o primeiro nome
nome_completo = nome.split()

print(nome_completo[0])

Heitor

> Quando usamos a posição `[-1]` em um vetor/array, o resultado sempre será o elemento presente na última posição.

In [ ]:
#Exibir somente o último nome

print(nome_completo[-1])

Oliveira

> Nesse exercício foi usado a função `str()` para converter o `len(nome)` para uma String, já que o valor gerado pelo `len(nome)` é um inteiro e o Python não aceita fazer a concatenação de Strings com Inteiros.

In [ ]:
#Sugestão de Simples de Nome de Usuário

nome_usuario = nome_completo[0] + "_" + nome_completo[-1] + str(len(nome))

print(f"Olá, {nome}! Segue o seu nome de usuário: {nome_usuario.lower()}")

Olá, Heitor da Silva de Oliveira! Segue o seu nome de usuário: heitor_oliveira27

## Atividade de fixação 1.7

Crie uma lista com pelo menos quatro produtos. Cada produto deve ser um dicionário contendo:

- nome;
- categoria;
- preço;
- estoque;
- situação ativa ou inativa.

Depois:

1. mostre o nome do segundo produto;
2. altere o estoque do primeiro;
3. adicione um novo produto;
4. crie um conjunto com as categorias sem repetição;
5. calcule o total de unidades em estoque.

In [ ]:
#Criando uma lista de pelo menos quatro produtos.

lista_produtos = [
    {"nome": "Banana", "categoria": "Fruta", "preco": 3.99, "estoque": 100, "situacao": "Ativo"},
    {"nome": "Batata", "categoria": "Legume", "preco": 1.99, "estoque": 5, "situacao": "Ativo"},
    {"nome": "Alface", "categoria": "Verdura", "preco": 5, "estoque": 50, "situacao": "Ativo"},
    {"nome": "Cenoura", "categoria": "Legume", "preco": 4.99, "estoque": 25, "situacao": "Ativo"},
    {"nome": "Tomate", "categoria": "Fruta", "preco": 2.99, "estoque": 0, "situacao": "Inativo"}
]

Foi gerada uma lista com 5 produtos, para exibir o nome do segundo produto é feito o seguinte:
- é chamada a `lista_produtos[1]`, sendo `lista_produtos` o nome da lista e o `[1]` a segunda posição da lista `(As listas começam com índice 0)`.
- junto do `lista_produtos[1]` é acrescentado o `["nome"]`, esse `["nome"]` vai estar chamando qual categoria será exibida.
- ou seja, em `lista_produtos[1]["nome"]` vai chamar o que está registrado na "coluna" `nome` na segunda posição da lista.

In [ ]:
#Exibindo o nome do segundo produto.
print(lista_produtos[1]["nome"])

Batata

Para alterar algum item existente de uma lista é feito um procedimento bem parecido quando vamos exibir uma coluna de algum item da lista.
> Foi feito o exercício de alterar o estoque do primeiro item da lista
- Primeiro, chamamos a lista, a posição e a coluna que queremos editar
  ```python
  lista_produtos[0]["estoque"]
  ```
- Após isso, usando o sinal de `=`, atribuímos o novo valor desse item:
  ```python
  lista_produtos[0]["estoque"] = 67
  ```
- Sendo assim, o produto que está presente no índice 0 terá um estoque de 67 unidades.

In [ ]:
#Alterar estoque do primeiro produto.
lista_produtos[0]["estoque"] = 67

print(f"O estoque do produto: {lista_produtos[0]["nome"]} é de {lista_produtos[0]["estoque"]} unidades.")

O estoque do produto: Banana é de 67 unidades.

TypeError: 'str' object cannot be interpreted as an integer

#1. Instalando uma biblioteca no Colab

In [ ]:
#No ambiente do Colab, é acrescentado o símbolo de % antes do comando pip.
%pip install -qU pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 49.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.6 which is incompatible.

In [ ]:
#Importando a biblioteca pandas no ambiente colab e dando o alias de "pd", afim de facilitar na hora de chamar a biblioteca.
#Foi feito o print com o comando ".__version__" para exibir qual versão que está sendo usada no projeto.
import pandas as pd
print(pd.__version__)

3.0.6

---

##1.1 Atividade de fixação
1. Importe `math` e calcule a raiz quadrada de um valor.
2. Use `statistics` para calcular média e mediana.
3. Use `random` para sortear um número.
4. Use `datetime` para mostrar data e hora.
5. Instale e importe `pandas`.

###Importando a biblioteca `math` no ambiente.

In [ ]:
import math

### Calculando a raiz quadrada de um valor usando a função `.sqrt()`, dentro do parênteses é inserido o valor desejado.

In [ ]:
math.sqrt(100)

10.0

###Importando a biblioteca `statistics` e dando o apelido de `stats` para facilitar o uso durante o código.

In [ ]:
import statistics as stats

###Dados fictícios para que sejam feitas as operações indicadas no enunciado.

In [ ]:
dados_stats = [50, 20, 40, 30, 10]

###Fazendo o cálculo de média usando a função `.mean()` da biblioteca `statistics`, o conjunto de dados deve ser inserido dentro do `()`.

In [ ]:
stats.mean(dados_stats)

30

###Fazendo o cálculo da mediana usando a função `.median()`, dentro do `()` deve ser inserido o conjunto de dados desejado.
> O cálculo de mediana trata de pegar o conjunto de dados, organizar em ordem crescente e selecionar o valor que ficou na posição do meio.

In [ ]:
stats.median(dados_stats)

30

###Importando a biblioteca random, presente no python para que seja feito o sorteio de algum número aleatório.

In [ ]:
import random

###Para que seja feito o sorteio é usado a função `.randint()` da biblioteca `random`, dentro do `()` é inserido o intervalo de números.
> Por exemplo: o `range` está como de 1 à 10, então o python vai sortear e escolher um número dentro do intervalo de 1 à 10.

In [ ]:
random.randint(1,9999999)

2732025

###Do framework `datetime` será importado a ferramenta `datetime`.

In [ ]:
from datetime import datetime

Exibindo a data e hora atuais usando a função `.now()`.

In [ ]:
agora = datetime.now()
print(agora)

2026-09-26 16:31:18.354700

Importando a biblioteca `pandas` dando o alias de `pd` para facilitar o uso durante o código.

In [ ]:
import pandas as pd

##1.2 Atividade de fixação
1. Crie uma lista de dicionários com cinco produtos.
2. Salve a lista em `produtos.json`.
3. Leia o arquivo novamente.
4. Mostre apenas produtos ativos.
5. Gere também um arquivo `produtos.csv`.
6. Trate o caso em que o arquivo não existe.

In [ ]:
#Criando a lista de dicionários com 5 produtos.
produtos = [
    {"nome": "Mouse", "preco": 80.0, "estoque": 10, "ativo": True},
    {"nome": "Teclado", "preco": 100.0, "estoque": 20, "ativo": False},
    {"nome": "Mousepad", "preco": 150.0, "estoque": 100, "ativo": False},
    {"nome": "Carregador", "preco": 25.5, "estoque": 5, "ativo": True},
    {"nome": "Monitor", "preco": 500.99, "estoque": 25, "ativo": True}
]

###Fazendo a operação de gravar a lista dos produtos em um arquivo json.
> A formatação do comando open é assim: nome do arquivo, operação desejada (se será feita a leitura ou gravação do arquivo), definir o encoding do arquivo.

In [ ]:
#Importando a biblioteca json.
import json

#O "w" no comando open vem de "write".
with open("produtos.json", "w", encoding = "utf-8") as arquivo:
  json.dump(
      produtos,
      arquivo,
      ensure_ascii = False,
      indent = 2
  )

###Importando o arquivo gerado no ambiente.
> A estrutura para ser feita a leitura de um arquivo é bem parecida, é usada a função open e dentro dela é inserida o nome do arquivo, o comando `"r"` para ser feita a leitura e o enconding.

In [ ]:
with open("produtos.json", "r", encoding = "utf-8") as arquivo:
  produto_carregado = json.load(arquivo)

#Leitura do arquivo carregado.
print(produto_carregado)

[{'nome': 'Mouse', 'preco': 80.0, 'estoque': 10, 'ativo': True}, {'nome': 'Teclado', 'preco': 100.0, 'estoque': 20, 'ativo': False}, {'nome': 'Mousepad', 'preco': 150.0, 'estoque': 100, 'ativo': False}, {'nome': 'Carregador', 'preco': 25.5, 'estoque': 5, 'ativo': True}, {'nome': 'Monitor', 'preco': 500.99, 'estoque': 25, 'ativo': True}]

In [ ]:
#Mostrar apenas produtos ativos.
print("Lista de produtos ativos:")
for produto in produto_carregado:
  if produto['ativo'] == True:
    print(f"{produto['nome']}")

Lista de produtos ativos:
Mouse
Carregador
Monitor

###Gerando um arquivo .csv
> Foi feita a adaptação da base de dados para o formato csv, ou seja, a primeira linha deve ser as colunas que serão usadas na base de dados e logo em seguida são as informações, respeitando as ordens das colunas citadas na primeira linha.

Novamente, foi usado o comando `open()` e atribuindo todo esse conteúdo para a variável `arquivo`, assim, fazendo todas as operações necessárias para o mesmo.

In [ ]:
import csv

produtos = [
    ["nome", "preco", "estoque", "ativo"],
    ["Mouse", 80.0, 10, True],
    ["Teclado", 100.0, 20, False],
    ["Mousepad", 150.0, 100, False],
    ["Carregador", 25.5, 5, True],
    ["Monitor", 500.99, 25, True]
]

with open("produtos.csv", "w", newline = "", encoding = "utf-8") as arquivo:
  escritor = csv.writer(arquivo)
  escritor.writerows(produtos)

###Fazendo a leitura e exibição do arquivo .csv gerado

In [ ]:
with open("produtos.csv", "r", encoding = "utf-8") as arquivo:
  leitor = csv.DictReader(arquivo)

  for linha in leitor:
    print(linha)

{'nome': 'Mouse', 'preco': '80.0', 'estoque': '10', 'ativo': 'True'}
{'nome': 'Teclado', 'preco': '100.0', 'estoque': '20', 'ativo': 'False'}
{'nome': 'Mousepad', 'preco': '150.0', 'estoque': '100', 'ativo': 'False'}
{'nome': 'Carregador', 'preco': '25.5', 'estoque': '5', 'ativo': 'True'}
{'nome': 'Monitor', 'preco': '500.99', 'estoque': '25', 'ativo': 'True'}

###Tratativa de erros caso o arquivo ainda não exista.
> Foi pedido que fosse feita a leitura de um arquivo não existente no projeto, chamado `configuracao.json`. Como o arquivo não existe, foram feitas as tratativas de erros.

In [ ]:
from json.decoder import JSONDecodeError
try:
  with open("configuracao.json", "r", encoding = "utf-8") as arquivo:
    configuracao = json.load(arquivo)
#Tratativa para caso o arquivo não seja encontrado.
except FileNotFoundError:
  configuracao = {}
  print("O arquivo ainda não existe, uma configuração vazia foi criada!")
#Tratativa para caso o JSON possua um formato inválido.
except JSONDecodeError:
  configuracao = {}
  print("O arquivo JSON possui um formato inválido.")

O arquivo ainda não existe, uma configuração vazia foi criada!

##1.3 Análise de vendas com Pandas
Crie um DataFrame ou leia um arquivo contendo as seguintes informações:

- nome do produto;
- categoria do produto;
- preço unitário;
- quantidade vendida;
- custo unitário.

Em seguida, realize as etapas abaixo:

1. visualize as primeiras linhas do DataFrame com `head()`;
2. verifique a estrutura, os tipos de dados e a presença de valores nulos com `info()`;
3. obtenha um resumo estatístico das colunas numéricas com `describe()`;
4. crie a coluna `faturamento`, calculada por:
    
    `preço × quantidade vendida`;
    
5. crie a coluna `custo_total`, calculada por:
    
    `custo unitário × quantidade vendida`;
    
6. crie a coluna `lucro_bruto`, calculada por:
    
    `faturamento − custo_total`;
    
7. filtre apenas os produtos que apresentaram lucro bruto positivo;
8. ordene os produtos do maior para o menor faturamento;
9. agrupe os dados por categoria e apresente o faturamento, o custo total e o lucro bruto de cada grupo;
10. salve o resultado final em um arquivo CSV.

O arquivo CSV deve ser salvo sem a coluna de índice.

In [ ]:
#Criação e exibição do dataframe.
import pandas as pd

produtos = [
    {"nome_produto": "Mouse", "categoria_produto": "Periférico", "preco_unitario": 10, "qtd_vendida": 100, "custo_unitario": 5},
    {"nome_produto": "Torraedira", "categoria_produto": "Eletrodoméstico", "preco_unitario": 100, "qtd_vendida": 50, "custo_unitario": 50},
    {"nome_produto": "Celular", "categoria_produto": "Eletrônico", "preco_unitario": 3000, "qtd_vendida": 200, "custo_unitario": 2000}
]

df = pd.DataFrame(produtos)
df

  nome_produto categoria_produto  preco_unitario  qtd_vendida  custo_unitario
0        Mouse        Periférico              10          100               5
1   Torraedira   Eletrodoméstico             100           50              50
2      Celular        Eletrônico            3000          200            2000

In [ ]:
#Exibição das primeiras linhas do DataFrame.
df.head()

  nome_produto categoria_produto  preco_unitario  qtd_vendida  custo_unitario
0        Mouse        Periférico              10          100               5
1   Torraedira   Eletrodoméstico             100           50              50
2      Celular        Eletrônico            3000          200            2000

In [ ]:
#Exibição da estrutura, tipos de dados e presença de valores nulos no DataFrame.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nome_produto       3 non-null      str
 1   categoria_produto  3 non-null      str
 2   preco_unitario     3 non-null      int64
 3   qtd_vendida        3 non-null      int64
 4   custo_unitario     3 non-null      int64
dtypes: int64(3), str(2)
memory usage: 312.0 bytes

In [ ]:
#Resumo estatístico do DataFrame.
df.describe()

       preco_unitario  qtd_vendida  custo_unitario
count        3.000000     3.000000        3.000000
mean      1036.666667   116.666667      685.000000
std       1700.891923    76.376262     1139.045653
min         10.000000    50.000000        5.000000
25%         55.000000    75.000000       27.500000
50%        100.000000   100.000000       50.000000
75%       1550.000000   150.000000     1025.000000
max       3000.000000   200.000000     2000.000000

In [ ]:
#Criação da coluna "Faturamento" usando como base o Preço Unitário dos produtos e a Quantidade Vendida.
df["faturamento"] = df["preco_unitario"] * df["qtd_vendida"]

#Exibição do DataFrame após essa operação de criação da coluna.
df

,nome_produto,categoria_produto,preco_unitario,qtd_vendida,custo_unitario,faturamento
0,Mouse,Periférico,10,100,5,1000
1,Torraedira,Eletrodoméstico,100,50,50,5000
2,Celular,Eletrônico,3000,200,2000,600000

In [ ]:
#Criação da coluna "custo_total" com base nas colunas "custo_unitario" e "quantidade_vendida"
df["custo_total"] = df["custo_unitario"] * df["qtd_vendida"]

#Exibição do resultado no DataFrame.
df

,nome_produto,categoria_produto,preco_unitario,qtd_vendida,custo_unitario,faturamento,custo_total
0,Mouse,Periférico,10,100,5,1000,500
1,Torraedira,Eletrodoméstico,100,50,50,5000,2500
2,Celular,Eletrônico,3000,200,2000,600000,400000

In [ ]:
#Criação da coluna "lucro_bruto" com base na diferença do "faturamento" com o "custo_total".
df["lucro_bruto"] = df["faturamento"] - df["custo_total"]

#Exibição do DataFrame após as alterações.
df

,nome_produto,categoria_produto,preco_unitario,qtd_vendida,custo_unitario,faturamento,custo_total,lucro_bruto
0,Mouse,Periférico,10,100,5,1000,500,500
1,Torraedira,Eletrodoméstico,100,50,50,5000,2500,2500
2,Celular,Eletrônico,3000,200,2000,600000,400000,200000

In [ ]:
#filtre apenas os produtos que apresentaram lucro bruto positivo;
bruto_positivo = df [df["lucro_bruto"] > 1000]

print(bruto_positivo)

  nome_produto categoria_produto  preco_unitario  qtd_vendida  custo_unitario  \
1   Torraedira   Eletrodoméstico             100           50              50
2      Celular        Eletrônico            3000          200            2000

   faturamento  custo_total  lucro_bruto
1         5000         2500         2500
2       600000       400000       200000