Fazendo a importação das bibliotecas necessárias para a aula.

In [47]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt

Importando a base de dados para o projeto e fazendo as verificações se foi importada corretamente.

In [48]:
df = pd.read_csv('dados_aula1_machine_learning_industria.csv')

In [49]:
df.head()

,timestamp,lote_producao,operador,modo_controle,status_valvula,setpoint_vazao_l_min,vazao_medida_l_min,pressao_linha_bar,temperatura_processo_c,abertura_valvula_pct,vibracao_bomba_mm_s,tempo_resposta_ms,ph_produto,densidade_produto_g_cm3,status_instrumentacao
0,2026-01-10 08:00:00,Lote_A,op_b,automatico,normal,121.44,128.08,3.518,95.00,56.97,2.960,220.8,7.09,1.069,estavel
1,2026-01-10 09:00:00,Lote_D,op_c,cascata,normal,126.17,119.32,4.616,43.34,63.26,2.532,402.1,6.99,1.053,inspecao
2,2026-01-10 10:00:00,Lote_B,op_d,manual,intermitente,128.54,129.11,4.118,40.67,63.14,2.182,284.1,6.72,1.021,inspecao
3,2026-01-10 11:00:00,Lote_C,op_a,automatico,intermitente,106.50,102.68,3.547,43.94,64.75,2.772,486.3,6.67,1.093,inspecao
4,2026-01-10 12:00:00,Lote_C,op_a,automatico,normal,101.59,NaN,4.085,102.00,83.82,3.173,283.3,6.66,1.004,estavel

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp                188 non-null    object
 1   lote_producao            188 non-null    object
 2   operador                 183 non-null    object
 3   modo_controle            183 non-null    object
 4   status_valvula           188 non-null    object
 5   setpoint_vazao_l_min     188 non-null    float64
 6   vazao_medida_l_min       176 non-null    float64
 7   pressao_linha_bar        178 non-null    float64
 8   temperatura_processo_c   178 non-null    float64
 9   abertura_valvula_pct     188 non-null    float64
 10  vibracao_bomba_mm_s      188 non-null    float64
 11  tempo_resposta_ms        177 non-null    float64
 12  ph_produto               180 non-null    float64
 13  densidade_produto_g_cm3  188 non-null    float64
 14  status_instrumentacao    188 non-null    object
dtypes: float64(9), object(6)
memory usage: 22.2+ KB

In [51]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
setpoint_vazao_l_min,188.0,119.056277,12.164116,90.340,110.3375,119.2300,126.9200,156.950
vazao_medida_l_min,176.0,119.571761,13.808622,90.230,110.2875,118.5650,128.7800,160.330
pressao_linha_bar,178.0,3.954781,0.842332,2.811,3.5655,3.8865,4.1190,10.200
temperatura_processo_c,178.0,43.874213,9.399248,26.070,40.0275,43.1750,46.6650,110.000
abertura_valvula_pct,188.0,58.468617,16.380992,18.010,46.7575,58.6000,67.7500,99.280
vibracao_bomba_mm_s,188.0,2.336059,0.958364,0.386,1.7935,2.2900,2.7210,9.100
tempo_resposta_ms,177.0,337.286441,129.197193,130.100,278.2000,321.4000,377.5000,1500.000
ph_produto,180.0,6.806500,0.312416,6.040,6.6100,6.8200,7.0125,7.560
densidade_produto_g_cm3,188.0,1.040255,0.030946,0.949,1.0210,1.0395,1.0620,1.134

Estrutura para relatórios básicos a respeito do dataset.
- `.shape` exibe as dimensões do dataset no formato de (linhas x colunas)
- `.dtypes` exibe uma lista de atribuitos e tipos de cada atribuito
- `.isna().sum()` resume a quantidade de valores faltantes
- `.duplicated().sum()` conta a quantidade de linhas idênticas no dataset

In [52]:
print(f"Dimensões base: {df.shape}")

print(f"\nTipos de dados: \n{df.dtypes}")

print(f"\nValores faltantes por coluna: \n{df.isna().sum()}")

print(f"\nQuantidade de linhas duplicadas: \n{df.duplicated().sum()}")

Dimensões base: (188, 15)

Tipos de dados:
timestamp                   object
lote_producao               object
operador                    object
modo_controle               object
status_valvula              object
setpoint_vazao_l_min       float64
vazao_medida_l_min         float64
pressao_linha_bar          float64
temperatura_processo_c     float64
abertura_valvula_pct       float64
vibracao_bomba_mm_s        float64
tempo_resposta_ms          float64
ph_produto                 float64
densidade_produto_g_cm3    float64
status_instrumentacao       object
dtype: object

Valores faltantes por coluna:
timestamp                   0
lote_producao               0
operador                    5
modo_controle               5
status_valvula              0
setpoint_vazao_l_min        0
vazao_medida_l_min         12
pressao_linha_bar          10
temperatura_processo_c     10
abertura_valvula_pct        0
vibracao_bomba_mm_s         0
tempo_resposta_ms          11
ph_produto                  8
densidade_produto_g_cm3     0
status_instrumentacao       0
dtype: int64

Quantidade de linhas duplicadas:
8

---
Fazendo as tratativas para preencher valores NaN.
> É aconselhado que para valores números seja preenchido com a mediana e valores categóricos sejam preenchidos com moda.

Preenchendo os valores NaN da coluna `operador` usando a moda (Valor com maior ocorrência) presente no dataset
> Será atribuído na coluna `operador` a coluna `operador` com as alterações desejadas
  - Nesse exemplo foi aplicado o `.fillna()`, dentro desse `.fillna()` foi feito a busca de qual era a moda da coluna `operador`, com o comando `.mode()` e, vendo a lista de modas da coluna, foi optado por usar a moda de índice 0.

In [53]:
df['operador'] = df['operador'].fillna(df['operador'].mode()[0])

In [54]:
df['modo_controle'] = df['modo_controle'].fillna(df['modo_controle'].mode()[0])

É possível fazer uma lista com as colunas que possuem valores nulos e fazer um laço de repetição para que seja feita todo esse processo em cada coluna dessa lista.
> No exemplo abaixo foi uma lista com as colunas categóricas, dessa lista foi feito um laço de repetição para que, cada coluna dessa lista que precise executar o `.fillna()`, seja feito a etapa de encontrar a moda e preencher com o primeiro item (índice 0) da lista de modas (que é o item que mais se repete).

In [55]:
categorias = ['lote_producao', 'operador', 'modo_controle', 'status_valvula']

for categoria in categorias:
  df[categoria] = df[categoria].fillna(df[categoria].mode()[0])

Todas as colunas categóricas atualmente possuem 0 linhas vazias.

In [56]:
df.isna().sum()

timestamp                   0
lote_producao               0
operador                    0
modo_controle               0
status_valvula              0
setpoint_vazao_l_min        0
vazao_medida_l_min         12
pressao_linha_bar          10
temperatura_processo_c     10
abertura_valvula_pct        0
vibracao_bomba_mm_s         0
tempo_resposta_ms          11
ph_produto                  8
densidade_produto_g_cm3     0
status_instrumentacao       0
dtype: int64

Para facilitar o processo de separar as colunas numéricas para as categóricas, pode-se usar o comando `.select_dtypes()`, dentro do parênteses será usado um `include = ` com a categoria desejada, por fim, inserir `.columns`, gerando uma lista que possua apenas o nome das colunas.
> Exemplo `df.select_dtypes(include = np.number).columns`<br>
> Caso queira que seja feito a lista das categórias, pode-se usar o `exclude` no lugar do `include`, assim, excluindo as colunas numéricas da lista de colunas exibidas.

In [57]:
df.select_dtypes(include = np.number).columns

Index(['setpoint_vazao_l_min', 'vazao_medida_l_min', 'pressao_linha_bar',
       'temperatura_processo_c', 'abertura_valvula_pct', 'vibracao_bomba_mm_s',
       'tempo_resposta_ms', 'ph_produto', 'densidade_produto_g_cm3'],
      dtype='object')

Repetindo o mesmo processo para as colunas numéricas, preenchendo os campos `NaN` com a mediana.

In [58]:
categorias_numericas = ['setpoint_vazao_l_min', 'vazao_medida_l_min', 'pressao_linha_bar', 'temperatura_processo_c', 'abertura_valvula_pct', 'vibracao_bomba_mm_s', 'tempo_resposta_ms', 'ph_produto', 'densidade_produto_g_cm3']

for categoria in categorias_numericas:
  df[categoria] = df[categoria].fillna(df[categoria].median())

In [59]:
df.isna().sum()

timestamp                  0
lote_producao              0
operador                   0
modo_controle              0
status_valvula             0
setpoint_vazao_l_min       0
vazao_medida_l_min         0
pressao_linha_bar          0
temperatura_processo_c     0
abertura_valvula_pct       0
vibracao_bomba_mm_s        0
tempo_resposta_ms          0
ph_produto                 0
densidade_produto_g_cm3    0
status_instrumentacao      0
dtype: int64

In [61]:
df.vazao_medida_l_min

0      128.080
1      119.320
2      129.110
3      102.680
4      118.565
        ...
183    110.300
184    111.880
185     92.760
186    120.360
187    118.290
Name: vazao_medida_l_min, Length: 188, dtype: float64

---
Calculando o IQR Manualmente

In [65]:
q1 = df['pressao_linha_bar'].quantile(0.25)

In [66]:
q3 = df['pressao_linha_bar'].quantile(0.75)

In [67]:
iqr = q3 - q1

In [68]:
lim_inf = q1 - 1.5 * iqr

In [69]:
lim_sup = q3 + 1.5 * iqr

In [75]:
print(f"Q1 (25%): {q1:.2f}\nQ3 (75%): {q3:.2f}\nIQR: {iqr:.2f}\nLimite Inferior: {lim_inf:.2f}\nLimite Superior: {lim_sup:.2f}")

Q1 (25%): 3.57
Q3 (75%): 4.11
IQR: 0.54
Limite Inferior: 2.75
Limite Superior: 4.92

In [76]:
df['pressao_linha_bar'].clip(lower = lim_inf, upper = lim_sup)

0      3.518
1      4.616
2      4.118
3      3.547
4      4.085
       ...
183    3.899
184    4.422
185    3.623
186    3.720
187    4.222
Name: pressao_linha_bar, Length: 188, dtype: float64